apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "myapp-chart.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "myapp-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "myapp-chart.name" . }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.app.containerPort }}
          env:
            - name: APP_GREETING
              valueFrom:
                configMapKeyRef:
                  name: {{ include "myapp-chart.fullname" . }}-config
                  key: APP_GREETING
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "myapp-chart.fullname" . }}-config
            items:
              - key: message_key.txt
                path: message_file.txt
