apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp-chart.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "myapp-chart.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.app.containerPort }}
      nodePort: {{ .Values.service.nodePort }}
